/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.demoneach;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {
    public static void main(String[] args) {
        log.info("Test");
    }
}
