/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.demoneach;

import static org.junit.jupiter.api.Assertions.assertEquals;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

@Slf4j
class AppTest {
    @Test
    void appHasAGreeting() {
        Integer i = 1;
        assertEquals(1, i);
    }
}
